import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,Check,ChevronDown,Code2,Globe2,MapPin,Menu,MessageCircle,MonitorSmartphone,Moon,PenTool,Search,ShieldCheck,Smartphone,Star,Sun,Users,Video, X,Zap,BarChart3,GraduationCap} from 'lucide-react';
import './styles.css';

const services=[
 ['Website Development','Professional school and college websites.','code'],['Google Business Profile Setup','Increase local visibility on Google Search and Maps.','globe'],['Search Engine Optimization (SEO)','Help institutions rank higher on Google.','search'],['Social Media Management','Facebook, Instagram and LinkedIn management.','users'],['Admission Landing Pages','Increase student inquiries and admissions.','graduation'],['Digital Branding','Professional logos, brochures, banners and branding.','pen'],['Photography & Videography','Campus photography, promotional videos and virtual tours.','video'],['Website Maintenance','Regular updates, backups and security.','shield']
];
const projects=[['Green Valley Public School','A conversion-focused school website with admissions, academics and campus storytelling.'],['Himalayan College','A modern college portal designed around programs, faculty and student inquiries.'],['Future Academy','A high-converting coaching institute presence built for lead generation.'],['Sunrise Senior Secondary School','A trust-first school website with news, events and parent-friendly navigation.']];
const faqs=[['How long does it take?','Most institutional websites launch in 2–4 weeks depending on scope, content and feedback cycles.'],['Do you redesign existing websites?','Yes. We can modernize an existing website while preserving useful content, SEO value and domain setup.'],['Can you manage our social media?','Yes. We can plan, design and publish institution-focused content for Facebook, Instagram and LinkedIn.'],['Do you provide hosting?','Yes. Hosting, SSL, domain guidance and deployment can be included depending on the package.'],['Can parents submit admission inquiries online?','Absolutely. We can build inquiry forms, WhatsApp CTAs, admission landing pages and online application flows.'],['Do you provide maintenance?','Yes. Ongoing updates, backups, security and content changes are available through maintenance plans.']];
const icons={code:Code2,globe:Globe2,search:Search,users:Users,graduation:GraduationCap,pen:PenTool,video:Video,shield:ShieldCheck};

function Logo(){return <a className="logo" href="#home" aria-label="NorthEast EduTech home"><span className="logo-mark"><GraduationCap size={20}/></span><span>NorthEast <b>EduTech</b></span></a>}
function App(){
 const [dark,setDark]=useState(false),[menu,setMenu]=useState(false),[open,setOpen]=useState(null),[top,setTop]=useState(false);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark); const on=()=>setTop(window.scrollY>500); window.addEventListener('scroll',on); return()=>window.removeEventListener('scroll',on)},[dark]);
 const go=(id)=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
 return <div>
 <header className="nav"><div className="container nav-in"><Logo/><nav className={menu?'open':''}>{['home','about','services','portfolio','pricing','faq','contact'].map(x=><a key={x} onClick={()=>go(x)} href={'#'+x}>{x[0].toUpperCase()+x.slice(1)}</a>)}<button className="theme" aria-label="Toggle dark mode" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="nav-cta" onClick={()=>go('contact')}>Free Consultation <ArrowRight size={16}/></button></nav><button className="mobile" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div></header>
 <main id="home">
 <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><span className="pulse"/> Built for Northeast India</span><h1>Empowering Educational Institutions <em>Across Northeast India</em></h1><p>Helping schools and colleges increase admissions, build trust, and grow online through modern digital solutions.</p><div className="actions"><button className="primary" onClick={()=>go('contact')}>Get Free Consultation <ArrowRight size={18}/></button><button className="secondary" onClick={()=>go('services')}>View Our Services</button></div><div className="trust"><span><Check size={15}/> Education focused</span><span><Check size={15}/> Fast delivery</span><span><Check size={15}/> Mobile first</span></div></div><div className="hero-art" aria-label="Illustration of an educational website on a laptop"><div className="glow"/><div className="browser"><div className="browser-top"><i/><i/><i/><span>school-portal.edu</span></div><div className="browser-body"><aside><div className="mini-logo"/><b>GREEN VALLEY</b><small>PUBLIC SCHOOL</small><div className="side-line active"/><div className="side-line"/><div className="side-line"/><div className="side-line"/></aside><div className="screen"><div className="screen-nav">Admissions <span>Academics</span><span>Campus</span><span>Contact</span><strong>Apply Now</strong></div><div className="screen-hero"><small>WELCOME TO OUR CAMPUS</small><h3>Learn. Grow.<br/><b>Lead the future.</b></h3><div className="screen-btn"/><div className="person p1"/><div className="person p2"/><div className="plant"/></div><div className="cards"><div/><div/><div/></div></div></div></div><div className="float-card"><div className="float-icon"><BarChart3 size={18}/></div><div><b>+42%</b><small>Inquiry growth</small></div></div></div></div></section>
 <section className="stats"><div className="container stat-grid">{['100% Responsive Websites','SEO Optimized','Google Friendly','Fast Delivery','Affordable Pricing'].map((s,i)=><div key={s}><strong>{i===0?'100%':i===1?'✓':i===2?'✓':i===3?'2–4':'₹'}</strong><span>{s.replace(/^[^ ]+ /,'')}</span></div>)}</div></section>
 <section id="about" className="section"><div className="container split"><div><span className="eyebrow">ABOUT NORTH﻿EAST EDUTECH</span><h2>Make your institution <em>visible, credible, and discoverable.</em></h2><p className="lead">NorthEast EduTech is a digital transformation startup helping schools, colleges, universities, coaching and skill-development institutes build a strong online presence.</p><p>From your first website to Google visibility, social media, branding and admission campaigns, we bring the digital pieces together into one practical growth system.</p><div className="mission"><div><small>MISSION</small><b>Make every educational institution in Northeast India digitally accessible and globally visible.</b></div><div><small>VISION</small><b>Become the leading digital partner for educational institutions in Northeast India.</b></div></div></div><div className="about-card"><div className="orb orb1"/><div className="orb orb2"/><GraduationCap size={52}/><h3>Digital-first education</h3><p>Modern technology, local understanding and measurable outcomes—built around the way parents and students discover institutions today.</p><div className="about-tags"><span>Web</span><span>SEO</span><span>Admissions</span><span>Brand</span></div></div></div></section>
 <section id="services" className="section soft"><div className="container"><div className="section-head"><div><span className="eyebrow">OUR SERVICES</span><h2>Everything your institution needs to <em>grow online.</em></h2></div><p>One partner for strategy, design, development, visibility and ongoing digital support.</p></div><div className="service-grid">{services.map(([t,d,k])=>{let I=icons[k];return <article className="service" key={t}><div className="icon"><I size={22}/></div><h3>{t}</h3><p>{d}</p><a onClick={()=>go('contact')} href="#contact">Explore <ArrowRight size={15}/></a></article>})}</div></div></section>
 <section id="portfolio" className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">SELECTED WORK</span><h2>Designed to turn <em>attention into action.</em></h2></div><p>Demo concepts showing how we can position different education brands online.</p></div><div className="portfolio-grid">{projects.map((p,i)=><article className="project" key={p[0]}><div className={'project-shot shot'+i}><div className="shot-browser"><span/><span/><span/></div><div className="shot-content"><small>{i===0?'ADMISSIONS OPEN':i===1?'EXPLORE PROGRAMS':i===2?'START LEARNING':'WELCOME TO CAMPUS'}</small><h3>{p[0]}</h3><div className="shot-bars"><i/><i/><i/></div></div><div className="shot-photo"/></div><div className="project-info"><span>Education / Digital Experience</span><h3>{p[0]}</h3><p>{p[1]}</p><button onClick={()=>go('contact')}>View Project <ArrowRight size={16}/></button></div></article>)}</div></div></section>
 <section id="pricing" className="section soft"><div className="container"><div className="center-head"><span className="eyebrow">SIMPLE PRICING</span><h2>Choose the level of <em>digital growth.</em></h2><p>Transparent starting points. Custom scopes available for institutions with specific requirements.</p></div><div className="price-grid"><Price name="Starter Website" price="₹20,000" items={['Up to 8 Pages','Responsive Design','Contact Form','Google Maps','Basic SEO','1 Month Support']}/><Price popular name="Professional Package" price="₹35,000" items={['Everything in Starter','Admission Inquiry Form','News & Events','Google Business Profile','Social Media Integration','Enhanced SEO','3 Months Support']}/><Price name="Premium Digital Package" price="₹60,000+" items={['Everything in Professional','Student Portal','Online Admission System','Custom Features','Analytics Dashboard','Priority Support','6 Months Maintenance']}/></div></div></section>
 <section className="section why"><div className="container"><div className="center-head"><span className="eyebrow">WHY US</span><h2>Built around what <em>education needs.</em></h2></div><div className="why-grid">{[['Professional Team','Clear communication and thoughtful execution.'],['Affordable Pricing','Premium digital work without agency-level overhead.'],['Fast Delivery','Focused processes that keep launches moving.'],['Education Expertise','Solutions designed for parents, students and administrators.'],['Responsive Support','A partner who stays available after launch.'],['SEO Optimized','Built to be discovered on Google from day one.'],['Modern UI/UX','Clean interfaces that build trust and clarity.'],['Secure Hosting','Performance, SSL, backups and reliable deployment.']].map(([t,d],i)=><div className="why-item" key={t}><div className="check"><Check size={16}/></div><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>
 <section className="section process soft"><div className="container"><div className="center-head"><span className="eyebrow">OUR PROCESS</span><h2>From first call to <em>live website.</em></h2></div><div className="timeline">{['Free Consultation','Requirement Analysis','Website Design','Development','Testing','Launch','Support'].map((s,i)=><div className="step" key={s}><div className="step-no">{i+1}</div><h3>{s}</h3>{i<6&&<div className="connector"/>}</div>)}</div></div></section>
 <section className="section testimonials"><div className="container"><div className="center-head"><span className="eyebrow">TRUSTED EXPERIENCE</span><h2>What education leaders <em>could say.</em></h2><p>Sample testimonials for the demo experience—replace these with your verified client feedback.</p></div><div className="testimonial-grid">{[['“The new website makes our school look as professional online as it feels on campus.”','School Administrator','★★★★★'],['“NorthEast EduTech helped us simplify admissions and make it much easier for parents to contact us.”','College Coordinator','★★★★★'],['“Their team understood our local audience and delivered quickly without compromising quality.”','Institute Director','★★★★★'],['“The combination of website, Google visibility and social media finally feels like one strategy.”','School Principal','★★★★★']].map(x=><article className="testimonial" key={x[1]}><div className="stars">{x[2]}</div><p>{x[0]}</p><div className="person-line"><div className="avatar">{x[1][0]}</div><div><b>{x[1]}</b><small>Northeast India</small></div></div></article>)}</div></div></section>
 <section id="faq" className="section faq soft"><div className="container narrow"><div className="center-head"><span className="eyebrow">FAQ</span><h2>Questions, <em>answered.</em></h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={'faq-item '+(open===i?'active':'')} key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><ChevronDown size={20}/></button>{open===i&&<p>{a}</p>}</div>)}</div></div></section>
 <section id="contact" className="section contact"><div className="container contact-grid"><div><span className="eyebrow">LET'S TALK</span><h2>Ready to digitally transform your <em>institution?</em></h2><p className="lead">Tell us what you want to improve. We’ll help you choose the right digital solution—without unnecessary complexity.</p><div className="contact-points"><div><div className="icon"><MessageCircle size={20}/></div><span><small>PHONE</small><b>+91 XXXXX XXXXX</b></span></div><div><div className="icon"><Globe2 size={20}/></div><span><small>EMAIL</small><b>hello@northeastedutech.in</b></span></div><div><div className="icon"><MapPin size={20}/></div><span><small>OFFICE</small><b>Arunachal Pradesh, Northeast India</b></span></div></div></div><form className="form" onSubmit={e=>{e.preventDefault();alert('Thanks! Your consultation request has been captured for this demo.')}}><h3>Book a free consultation</h3><p>We usually respond within one business day.</p><div className="form-row"><label>Name<input required placeholder="Your name"/></label><label>Institution Name<input required placeholder="School / College name"/></label></div><div className="form-row"><label>Phone<input required type="tel" placeholder="+91"/></label><label>Email<input type="email" placeholder="you@example.com"/></label></div><label>Message<textarea rows="5" placeholder="Tell us about your institution and goals..."/></label><button className="primary" type="submit">Send Consultation Request <ArrowRight size={18}/></button></form></div></section>
 <section className="map"><div className="container"><div className="map-placeholder"><MapPin size={34}/><h3>Arunachal Pradesh, Northeast India</h3><p>Google Map embed placeholder — replace with your exact office location.</p><span>Open in Google Maps <ArrowRight size={15}/></span></div></div></section>
 <section className="cta"><div className="container cta-in"><div><span className="eyebrow">READY WHEN YOU ARE</span><h2>Give your institution the digital presence it deserves.</h2></div><button className="light-btn" onClick={()=>go('contact')}>Book a Free Consultation <ArrowRight size={18}/></button></div></section>
 </main>
 <footer><div className="container footer-grid"><div><Logo/><p>Digital transformation for educational institutions across Northeast India.</p><div className="socials"><span>f</span><span>in</span><span>◎</span></div></div><div><h4>Quick Links</h4><a href="#about">About</a><a href="#services">Services</a><a href="#portfolio">Portfolio</a><a href="#pricing">Pricing</a></div><div><h4>Services</h4><a href="#services">Website Development</a><a href="#services">SEO</a><a href="#services">Google Business</a><a href="#services">Social Media</a></div><div><h4>Contact</h4><a href="#contact">Free Consultation</a><a href="#contact">hello@northeastedutech.in</a><a href="#contact">Arunachal Pradesh</a></div></div><div className="container copyright">© 2026 NorthEast EduTech. All Rights Reserved.<span>Made for education. Built for growth.</span></div></footer>
 <a className="whatsapp" href="https://wa.me/91XXXXXXXXXX" aria-label="WhatsApp"><MessageCircle/></a>{top&&<button className="top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top">↑</button>}<button className="chat" onClick={()=>go('contact')}><MessageCircle size={17}/> Live Chat</button>
 </div>
}
function Price({name,price,items,popular}){return <article className={'price '+(popular?'popular':'')}>{popular&&<span className="badge">MOST POPULAR</span>}<span className="price-label">{name}</span><h3>{price}</h3><p>One-time setup + support</p><hr/>{items.map((x,i)=><div className="price-item" key={x}><Check size={16}/><span>{x}</span></div>)}<button className={popular?'primary':'secondary'} onClick={()=>document.getElementById('contact')?.scrollIntoView({behavior:'smooth'})}>Get Started <ArrowRight size={16}/></button></article>}
createRoot(document.getElementById('root')).render(<App/>);
